interface MenuItem {
  id: number
  name: string
  options: string[]
  addons: number[]
  dietary: string[]
  price: number
  image: string
}

interface MenuCategory {
  id: number
  category: string
  items: MenuItem[]
}

export const menuCategories: MenuCategory[] = [
  {
    id: 1,
    category: 'Starter',
    items: [
      {
        id: 1,
        name: 'Satay',
        options: ['Chicken', 'Beef'],
        addons: [0.0, 0.0],
        price: 19.00,
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 2,
        name: 'Chicken Wings',
        price: 14.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 3,
        name: 'Spring Rolls',
        price: 12.50,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 4,
        name: 'Fried Won Tons',
        price: 12.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 5,
        name: 'Deep Fried Tofu',
        price: 13.50,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 6,
        name: 'Sweet Corn Soup',
        price: 12.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 7,
        name: 'Won Ton Soup',
        price: 12.50,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 8,
        name: 'Achar',
        dietary: ['VG'],
        price: 12.00,
        options: [],
        addons: [],
        image: '/images/satay.jpg',
      }
    ]
  },
  {
    id: 2,
    category: 'Noodles',
    items: [
      {
        id: 9,
        name: 'Mee Goreng',
        options: ['Chicken', 'Seafood'],
        addons: [0.0, 0.0],
        price: 20.00,
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 10,
        name: 'Nasi Goreng',
        price: 20.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 26,
        name: 'Hokkien Mee',
        price: 20.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 27,
        name: 'Char Kuey Teow',
        price: 20.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 28,
        name: 'Wat Tan Hor',
        price: 21.50,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 29,
        name: 'Teo Chew Noodle Soup',
        options: ['Egg Noodle', 'Rice Noodle'],
        addons: [0.0, 0.0],
        price: 20.00,
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 24,
        name: 'Sin Chew Mee Hoon',
        price: 20.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
    ]
  },
  {
    id: 3,
    category: 'Main',
    items: [
      {
        id: 11,
        name: 'Roti Chanai',
        options: ['Chicken', 'Vege'],
        addons: [0.0, 0.0],
        price: 15.50,
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 12,
        name: 'Chicken Rendang',
        price: 21.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 13,
        name: 'Beef Rendang',
        price: 24.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 14,
        name: 'Nasi Lemak',
        options: ['Chicken', 'Beef'],
        addons: [0.0, 2.00],
        price: 21.00,
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 15,
        name: 'Chicken Sambal',
        price: 21.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 16,
        name: 'Prawn Sambal',
        price: 23.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 17,
        name: 'Curry Laksa',
        price: 20.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 18,
        name: 'Seafood Laksa',
        price: 21.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 19,
        name: 'Seafood Curry',
        price: 22.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 20,
        name: 'Chicken Curry',
        price: 21.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 21,
        name: 'Lamb Curry',
        price: 22.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 22,
        name: 'Kung Po Chicken / Beef',
        options: ['Chicken', 'Beef'],
        addons: [0.0, 2.0],
        price: 21.00,
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 23,
        name: 'Sweet & Sour Chicken',
        price: 21.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 25,
        name: 'Hainanese Chicken Rice',
        options: ['Fried Chicken', 'Steamed Chicken'],
        addons: [0.0, 0.0],
        price: 21.00,
        dietary: [],
        image: '/images/satay.jpg',
      }
    ]
  },
  {
    id: 4,
    category: 'Vegetarian',
    items: [
      {
        id: 30,
        name: 'Vegetarian Curry',
        dietary: ['VG'],
        price: 18.50,
        options: [],
        addons: [],
        image: '/images/satay.jpg',
      },
      {
        id: 31,
        name: 'Vegetarian Sin Chew Mee Hoon',
        dietary: ['VG'],
        price: 19.50,
        options: [],
        addons: [],
        image: '/images/satay.jpg',
      },
      {
        id: 32,
        name: 'Vegetarian Mee Goreng',
        dietary: ['VG'],
        price: 19.50,
        options: [],
        addons: [],
        image: '/images/satay.jpg',
      },
      {
        id: 33,
        name: 'Stir Fried Vegetables',
        dietary: ['VG'],
        price: 19.50,
        options: [],
        addons: [],
        image: '/images/satay.jpg',
      },
      {
        id: 34,
        name: 'Vegetarian Laksa',
        dietary: ['VG'],
        price: 19.50,
        options: [],
        addons: [],
        image: '/images/satay.jpg',
      }
    ]
  },
  {
    id: 5,
    category: 'Extras',
    items: [
      {
        id: 35,
        name: 'Plain Roti',
        price: 4.00,
        options: [],
        dietary: [],
        addons: [],
        image: '/images/satay.jpg',
      },
      {
        id: 36,
        name: 'Steamed Rice',
        price: 4.00,
        options: [],
        dietary: [],
        addons: [],
        image: '/images/satay.jpg',
      },
      {
        id: 37,
        name: 'Steamed Vegetables',
        price: 6.00,
        options: [],
        dietary: [],
        addons: [],
        image: '/images/satay.jpg',
      },
      {
        id: 38,
        name: 'Coconut Rice',
        price: 4.50,
        options: [],
        dietary: [],
        addons: [],
        image: '/images/satay.jpg',
      },
      {
        id: 39,
        name: 'Peanut Sauce',
        price: 4.00,
        options: [],
        dietary: [],
        addons: [],
        image: '/images/satay.jpg',
      }
    ]
  },
  {
    id: 6,
    category: 'Drinks',
    items: [
      {
        id: 40,
        name: 'Bundaberg',
        price: 5.00,
        options: ['Ginger Beer', 'Lemon Lime & Bitters'],
        addons: [0.0, 0.0],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 41,
        name: 'Soft drink',
        price: 3.50,
        options: ['Coke', 'Diet Coke', 'Sprite', 'Fanta'],
        addons: [0.0, 0.0, 0.0, 0.0],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 42,
        name: 'Juice',
        price: 4.00,
        options: ['Apple', 'Orange', 'Mango', 'Pineapple'],
        addons: [0.0, 0.0, 0.0, 0.0],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 43,
        name: 'Coconut Water',
        price: 4.00,
        options: [],
        addons: [],
        dietary: [],
        image: '/images/satay.jpg',
      },
      {
        id: 44,
        name: 'Tea',
        price: 3.00,
        options: ['Jasmine', 'Green'],
        addons: [0.0, 0.0],
        dietary: [],
        image: '/images/satay.jpg',
      }
    ]
  }
]