interface MenuItem {
  id: number
  name: string
  options: string[]
  dietary: string[]
  price: number
  image: string
}

export const menuItems: MenuItem[] = [
  {
    id: 1,
    name: 'Satay',
    options: ['Chicken', 'Beef'],
    price: 1750,
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 2,
    name: 'Chicken Wings',
    price: 1300,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 3,
    name: 'Spring Rolls',
    price: 1150,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 4,
    name: 'Fried Won Tons',
    price: 1100,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 5,
    name: 'Deep Fried Tofu',
    price: 1250,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 6,
    name: 'Sweet Corn Soup',
    price: 1100,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 7,
    name: 'Won Ton Soup',
    price: 1150,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 8,
    name: 'Achar',
    dietary: ['VG'],
    price: 1100,
    options: [],
    image: '/images/satay.jpg',
  },
  {
    id: 9,
    name: 'Mee Goreng',
    options: ['Chicken', 'Seafood'],
    price: 1900,
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 10,
    name: 'Nasi Goreng',
    price: 1900,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 11,
    name: 'Roti Chanai',
    options: ['Chicken', 'Vege'],
    price: 1450,
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 12,
    name: 'Chicken Rendang',
    price: 2000,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 13,
    name: 'Beef Rendang',
    price: 2000,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 14,
    name: 'Nasi Lemak',
    options: ['Chicken', 'Beef'],
    price: 2000,
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 15,
    name: 'Chicken Sambal',
    price: 2000,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 16,
    name: 'Prawn Sambal',
    price: 2150,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 17,
    name: 'Curry Laksa',
    price: 1900,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 18,
    name: 'Seafood Laksa',
    price: 2000,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 19,
    name: 'Seafood Curry',
    price: 2100,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 20,
    name: 'Chicken Curry',
    price: 2100,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 21,
    name: 'Lamb Curry',
    price: 2100,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 22,
    name: 'Kung Po Chicken / Beef',
    options: ['Chicken', 'Beef'],
    price: 2000,
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 23,
    name: 'Sweet & Sour Chicken',
    price: 2000,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 24,
    name: 'Sin Chew Mee Hoon',
    price: 1900,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 25,
    name: 'Hainanese Chicken Rice',
    options: ['Fried Chicken', 'Steamed Chicken'],
    price: 2000,
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 26,
    name: 'Hokkien Mee',
    price: 2000,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 27,
    name: 'Char Kuey Teow',
    price: 1900,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 28,
    name: 'Wat Tan Hor',
    price: 2050,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 29,
    name: 'Teo Chew Noodle Soup',
    options: ['Egg Noodle', 'Rice Noodle'],
    price: 1900,
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 30,
    name: 'Vegetarian Curry',
    dietary: ['VG'],
    price: 1850,
    options: [],
    image: '/images/satay.jpg',
  },
  {
    id: 31,
    name: 'Vegetarian Sin Chew Mee Hoon',
    dietary: ['VG'],
    price: 1850,
    options: [],
    image: '/images/satay.jpg',
  },
  {
    id: 32,
    name: 'Vegetarian Mee Goreng',
    dietary: ['VG'],
    price: 1850,
    options: [],
    image: '/images/satay.jpg',
  },
  {
    id: 33,
    name: 'Stir Fried Vegetables',
    dietary: ['VG'],
    price: 1850,
    options: [],
    image: '/images/satay.jpg',
  },
  {
    id: 34,
    name: 'Vegetarian Laksa',
    dietary: ['VG'],
    price: 1850,
    options: [],
    image: '/images/satay.jpg',
  },
  {
    id: 35,
    name: 'Plain Roti',
    price: 400,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 36,
    name: 'Steamed Rice',
    price: 400,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 37,
    name: 'Steamed Vegetables',
    price: 600,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 38,
    name: 'Coconut Rice',
    price: 450,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
  {
    id: 39,
    name: 'Peanut Sauce',
    price: 400,
    options: [],
    dietary: [],
    image: '/images/satay.jpg',
  },
]
